trigger:
  branches:
    include:
      - master
  paths:
    include:
      - SignalR-Web/*
      - azure-web-pipelines.yml

variables:
  dockerTag: $(date '+%Y%m%d').$(Version.Revision)
  Version.MajorMinor: 1.0
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]
  MyRunNumber: '1.0.0-CI-$(Date:yyyyMMdd).$(Rev:.r)'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: | 
      echo $(dockerTag)
      echo $(Build.BuildId)
      echo $(MyRunNumber)
      echo $(Version.Revision)
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: 'Docker Hub - Goncalvesj'
      repository: 'goncalvesj/signalr-web'
      command: build
      Dockerfile: '**/Dockerfile'
      tags: '$(dockerTag).$(Version.Revision)'

  # - task: Docker@1
  #   displayName: 'Build an image'
  #   inputs:
  #     azureSubscriptionEndpoint: $(AzureSubscription)
  #     azureContainerRegistry: $(ContainerRegistry)
  #     imageName: 'goncalvesj/signalr-web:$(Build.BuildId)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Charts'
    inputs:
      targetPath: 'SignalR-Web/helm'
      artifact: 'charts'
