trigger:
  branches:
    include:
      - master
  paths:
    include:
      - SignalR-Web/*
      - azure-web-pipelines.yml

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
        # - task: Docker@2
        #   displayName: 'Docker Build'
        #   inputs:
        #     containerRegistry: 'Docker Hub - Goncalvesj'
        #     repository: 'goncalvesj/signalr-web'
        #     command: build
        #     Dockerfile: '**/Dockerfile'
        #     tags: $(Build.BuildNumber)

        # - task: Docker@2
        #   displayName: 'Docker Push'
        #   inputs:
        #     containerRegistry: 'Docker Hub - Goncalvesj'
        #     repository: 'goncalvesj/signalr-web'
        #     command: push
        #     Dockerfile: '**/Dockerfile'
        #     tags: $(Build.BuildNumber)
    # - task: Docker@1
    #   displayName: 'Build an image'
    #   inputs:
    #     azureSubscriptionEndpoint: $(AzureSubscription)
    #     azureContainerRegistry: $(ContainerRegistry)
    #     imageName: 'goncalvesj/signalr-web:$(Build.BuildId)'

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Charts'
          inputs:
            targetPath: 'SignalR-Web/helm'
            artifact: 'charts'

- stage: Deploy
  displayName: 'Deploy'
  jobs:
  - deployment: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'V1-JoaoGoncalves-AKS'
    strategy:      
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Pipeline Artifact'
            inputs:
              artifactName: charts
          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: 'latest'
          - task: HelmDeploy@0
            displayName: 'Init Helm'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'V1-JoaoGoncalves-AKS-V1-JoaoGoncalves-AKS-default-1583626081772'
              command: 'init'
          
          # - task: HelmDeploy@0
          #   displayName: 'helm upgrade'
          #   inputs:
          #     azureSubscription: $(subscription)
          #     azureResourceGroup: $(resourceGroup)
          #     kubernetesCluster: $(kubernetesCluster)
          #     command: upgrade
          #     chartType: FilePath
          #     chartPath: '$(Pipeline.Workspace)/charts/${{ parameters.imageName }}'
          #     releaseName: ${{ parameters.releaseName }}
          #     valueFile: '$(Pipeline.Workspace)/charts/${{ parameters.imageName }}/values.yaml'
          #     arguments: '--set image.tag=$(Build.BuildId) --set image.repository=${{ parameters.repositoryName }}/${{ parameters.imageName }}'
          - task: HelmDeploy@0
            displayName: 'Install'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'V1-JoaoGoncalves-AKS-V1-JoaoGoncalves-AKS-default-1583626081772'
              namespace: 'default'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Pipeline.Workspace)/charts/signalr-web'
              releaseName: 'sw-0'
              overrideValues: '--set image.tag=$(Build.BuildNumber) --set image.repository=goncalvesj/signalr-web'
              valueFile: '$(Pipeline.Workspace)/charts/signalr-web/values.yaml'