trigger:
  branches:
    include:
      - master
  paths:
    include:
      - SignalR-Web/*
      - azure-web-pipelines.yml

variables:
  dockerTag: $(date '+%Y%m%d')

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: echo $(dockerTag) 
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: 'Docker Hub - Goncalvesj'
      repository: 'goncalvesj/signalr-web'
      command: build
      Dockerfile: '**/Dockerfile'
      tags: $(rev:.r)

  # - task: Docker@1
  #   displayName: 'Build an image'
  #   inputs:
  #     azureSubscriptionEndpoint: $(AzureSubscription)
  #     azureContainerRegistry: $(ContainerRegistry)
  #     imageName: 'goncalvesj/signalr-web:$(Build.BuildId)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Charts'
    inputs:
      targetPath: 'SignalR-Web/helm'
      artifact: 'charts'
